# Generated by Django 5.1.1 on 2024-10-30 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_condregistro_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='condregistro',
            new_name='codregistro',
        ),
    ]
